name: CI User_Progect

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]



jobs:
  lint-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort mypy pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run linters
      run: |
        flake8 app/
        black --check app/
        isort --check app/
        mypy app/

    - name: Run tests
      run: |
        pytest app/tests/ -v
        
    - name: Build Docker
      run: docker-compose build